<jsp:root
        xmlns:fmt="http://java.sun.com/jsp/jstl/fmt"
        xmlns:c="http://java.sun.com/jsp/jstl/core"
        xmlns:jsp="http://java.sun.com/JSP/Page"
        xmlns:fn="http://java.sun.com/jsp/jstl/functions"
        xmlns:collab="http://climatecolab.org/tags/collab_1.0"
        version="2.0">

    <jsp:directive.attribute name="seriesValues" type="org.xcolab.portlets.proposals.impact.ProposalImpactSeriesValues" required="true" rtexprvalue="true" description="seriesValues"/>
    <jsp:directive.attribute name="seriesName" required="true" rtexprvalue="true" description="seriesName"/>
    <jsp:directive.attribute name="impactIterations" type="java.util.List" required="true" rtexprvalue="true" description="impactIterations"/>
    <jsp:directive.attribute name="seriesNameClass" required="false" rtexprvalue="true" description="seriesNameClass"/>


    <td class="${seriesNameClass}">${seriesName}</td>
    <c:catch var="catchException">
        <c:forEach var="impactIteration" items="${impactIterations}">
            <fmt:formatNumber var="value"
                              value="${seriesValues.yearToValueMap[impactIteration.year]}"
                              maxFractionDigits="2"
                              groupingUsed="false"/>
            <td class="impact-value" data-attr-year="${impactIteration.year}">${value}</td>
        </c:forEach>
    </c:catch>

    <c:if test = "${catchException != null}">
        <p>The exception is : ${catchException} <br />
            There is an exception: ${catchException.message}</p>
    </c:if>


</jsp:root>